disabled_rules: # rule identifiers to exclude from running
  - force_cast
  - trailing_whitespace
  - line_length
  - variable_name
  - valid_docs

opt_in_rules: # some rules are only opt-in
  - missing_docs

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

file_length:
  warning: 1000
  error: 10000

# rules configuration
type_body_length:
  - 1000 # warning
  - 2000 # error
force_try: warning
function_body_length:
  - 300 # warning
  - 500 # error
function_parameter_count:
  - 20 # warning
  - 30 # error
cyclomatic_complexity:
  - 30 # warning
  - 50 # error

